In [2]:
from __future__ import print_function
import os
# Type Path
data_path = [r'C:\Users\wpghk\ai_data']

import pandas as pd
import numpy as np
from time import time
start = time()

filepath = os.sep.join(data_path + ['Iris_Data.csv'])
data = pd.read_csv(filepath)

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier 

le = LabelEncoder()
data['species'] = le.fit_transform(data.species)
feature_cols = data.columns[:-1]

# Get the split indexes
strat_shuf_split = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=42)

train_idx, test_idx = next(strat_shuf_split.split(data[feature_cols], data.species))

# Create the dataframes
X_train = data.loc[train_idx, feature_cols]
y_train = data.loc[train_idx, 'species']

X_test  = data.loc[test_idx, feature_cols]
y_test  = data.loc[test_idx, 'species']

def print_score(classifier, X_train, y_train, X_test, y_test, train = True):
    print("-"*100)
    if train == True:
        y_pred = classifier.predict(X_train)
        print("Training result:\n")
        print("Accuracy Score: {0:.4f}\n".format(accuracy_score(y_train, y_pred)))
        print("Classification Report:\n{}\n".format(classification_report(y_train, y_pred)))
        print("Confusion Matrix:\n{}\n".format(confusion_matrix(y_train, y_pred)))
        res = cross_val_score(classifier, X_train, y_train, cv = 10, n_jobs= -1, scoring ="accuracy")
        print("Average Accuracy:\t{0:.4f}\n".format(res.mean()))
        print("Standard Deviation:\t{0:.4f}".format(res.std()))
    elif train == False:
        y_pred = classifier.predict(X_test)
        print("Test result:\n")
        print("Accuracy Score: {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
        print("Classification Report:\n{}\n".format(classification_report(y_test, y_pred)))
        print("Confusion Matrix:\n{}\n".format(confusion_matrix(y_test, y_pred)))
        

from sklearn.ensemble import GradientBoostingClassifier

gdbc = GradientBoostingClassifier(random_state = 42)
gdbc.fit(X_train, y_train)


print_score(mnb ,X_train,y_train,X_test,y_test, train = True)
print_score(mnb ,X_train,y_train,X_test,y_test, train = False)

print("time: %.2f" % (time()-start))

----------------------------------------------------------------------------------------------------
Training result:

Accuracy Score: 0.9524

Classification Report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        35
          1       0.94      0.91      0.93        35
          2       0.92      0.94      0.93        35

avg / total       0.95      0.95      0.95       105


Confusion Matrix:
[[35  0  0]
 [ 0 32  3]
 [ 0  2 33]]

Average Accuracy:	0.9417

Standard Deviation:	0.0488
----------------------------------------------------------------------------------------------------
Test result:

Accuracy Score: 0.9778

Classification Report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       0.94      1.00      0.97        15
          2       1.00      0.93      0.97        15

avg / total       0.98      0.98      0.98        45


Confusion Matrix:
[[15  0