In [1]:
from __future__ import print_function
import os
# Type Path
data_path = [r'C:\Users\wpghk\ai_data']

import pandas as pd
import numpy as np
from time import time
start = time()


filepath = os.sep.join(data_path + ['Human_Activity_Recognition_Using_Smartphones_Data.csv'])
data = pd.read_csv(filepath, sep=',')

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier 


le = LabelEncoder()
data['Activity'] = le.fit_transform(data.Activity)


feature_cols = data.columns[:-1]
corr_values = data[feature_cols].corr()
# Get the split indexes
strat_shuf_split = StratifiedShuffleSplit(n_splits=1, 
                                          test_size=0.2, 
                                          random_state=42)

train_idx, test_idx = next(strat_shuf_split.split(data[feature_cols], data.Activity))

# Create the dataframes
X_train = data.loc[train_idx, feature_cols]
y_train = data.loc[train_idx, 'Activity']

X_test  = data.loc[test_idx, feature_cols]
y_test  = data.loc[test_idx, 'Activity']

def print_score(classifier, X_train, y_train, X_test, y_test, train = True):
    print("-"*100)
    if train == True:
        y_pred = classifier.predict(X_train)
        print("Training result:\n")
        print("Accuracy Score: {0:.4f}\n".format(accuracy_score(y_train, y_pred)))
        print("Classification Report:\n{}\n".format(classification_report(y_train, y_pred)))
        print("Confusion Matrix:\n{}\n".format(confusion_matrix(y_train, y_pred)))
  #      res = cross_val_score(classifier, X_train, y_train, cv = 10, n_jobs= -1, scoring ="accuracy")
   #     print("Average Accuracy:\t{0:.4f}\n".format(res.mean()))
    #    print("Standard Deviation:\t{0:.4f}".format(res.std()))
    elif train == False:
        y_pred = classifier.predict(X_test)
        print("Test result:\n")
        print("Accuracy Score: {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
        print("Classification Report:\n{}\n".format(classification_report(y_test, y_pred)))
        print("Confusion Matrix:\n{}\n".format(confusion_matrix(y_test, y_pred)))
        

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

print_score(logreg ,X_train,y_train,X_test,y_test, train = True)
print_score(logreg ,X_train,y_train,X_test,y_test, train = False)

print("time: %.2f" % (time()-start))

C:\Users\wpghk\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


----------------------------------------------------------------------------------------------------
Training result:

Accuracy Score: 0.9877

Classification Report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1555
          1       0.96      0.97      0.97      1421
          2       0.97      0.97      0.97      1525
          3       1.00      1.00      1.00      1378
          4       1.00      1.00      1.00      1125
          5       1.00      1.00      1.00      1235

avg / total       0.99      0.99      0.99      8239


Confusion Matrix:
[[1555    0    0    0    0    0]
 [   0 1373   48    0    0    0]
 [   0   51 1474    0    0    0]
 [   0    0    0 1377    0    1]
 [   0    0    0    0 1125    0]
 [   0    0    0    1    0 1234]]

----------------------------------------------------------------------------------------------------
Test result:

Accuracy Score: 0.9869

Classification Report:
             precision    