# Classification Project

## File IO

Only File IO...

You may not change this code.

In [33]:
from tkinter.filedialog import askopenfilename
import pandas as pd
import tkinter
import os

tk_window = tkinter.Tk()
cwd = os.getcwd()

tr_data = pd.read_csv(askopenfilename(title='Choose your training data'))

tr_ans = pd.read_csv(askopenfilename(title='Choose your training answer'))

tr_ans = tr_ans.iloc[:, 0]

ts_data = pd.read_csv(askopenfilename(title='Choose your test data'))

tk_window.destroy()



## Predict Algorithm

Type your source code (Champion Algorithm)

In [35]:
from sklearn.preprocessing import LabelEncoder, LabelBinarizer

le =LabelBinarizer()
tr_data['department'] = le.fit_transform(tr_data.department)
ts_data['department'] = le.fit_transform(ts_data.department)

tr_data.drop(['number_of_projects'], axis = 1, inplace =True)
ts_data.drop(['number_of_projects'], axis = 1, inplace =True)


In [38]:
import warnings
warnings.filterwarnings('ignore', module='sklearn')

from sklearn.preprocessing import MinMaxScaler

msc =  MinMaxScaler()

tr_data = pd.DataFrame(msc.fit_transform(tr_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)

ts_data = pd.DataFrame(msc.fit_transform(ts_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)

k = len(tr_ans)
n_k = k
if k > 5600 :
    n_k = 5500
elif k >= 3750 :
    n_k = 203
elif k >= 2500 :
    n_k = 927
else :
    n_k = k//4;
    
print("data size: %d, k_size: %d" %(k,n_k));


from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=n_k, weights='distance',leaf_size=100, algorithm='kd_tree',n_jobs=-1)

knn = knn.fit(tr_data, tr_ans)

y_pred = knn.predict(ts_data)

pred_df = pd.DataFrame(y_pred)

pred_df.to_csv("output.csv", mode='w')

# End of Demo

data size: 2999, k_size: 927


## Check Accuracy

Only for check accuracy

In [37]:
def accuracy(real, predict):
    return sum(real == predict) / float(real.shape[0])

tk_window = tkinter.Tk()
cwd = os.getcwd()
ts_ans = pd.read_csv(askopenfilename(title='Choose your test answer'))
ts_ans = ts_ans.iloc[:, 0]
tk_window.destroy()

print(accuracy(ts_ans, y_pred))

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(accuracy(ts_ans, y_pred))
print("Confusion Matrix:\n{}\n".format(confusion_matrix(ts_ans, y_pred)))

0.53775
0.53775
Confusion Matrix:
[[  65  612  324]
 [   2 4458 1408]
 [   2 3199 1930]]

